#aws 때문에 빌드시 오류뜨는거 방지용인데 잘안됨 수정해야함
logging:
  level:
    #    org:
    #      hibernate:
    #        type:
    #          descriptor:
    #            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#db connection
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amugeona # github 업로드를 위해 변경
    username: ssafy
    password: ssafy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  #multifile upload 한도 50MB
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#aws 설정
cloud:
  aws:
    s3:
      bucket: amugeona
    credentials:
      access-key: access-key # github업로드를 위해 변경
      secret-key: secret-key
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
